cards/urls.py
from django.urls import path

from .views import StartQuizView, CardView, AddQuestion


app_name = "cards"
urlpatterns = [
    path("", StartQuizView.as_view(), name="start_quiz"),
    path("card/", CardView.as_view(), name="card"),
    path("add/", AddQuestion.as_view(), name="add"),
]

prepacards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("cards/", include("cards.urls", namespace="cards")),
    path("admin/", admin.site.urls),
]

cards/models.py
from django.db import models

# Create your models here.
class Subject(models.Model):

    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Chapter(models.Model):

    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    name = models.CharField(max_length=256)

    class YearTextChoice(models.TextChoices):
        MP2I = "1", "MP2I"
        MPI  = "2", "MPI"
    year = models.CharField(
        max_length=1,
        choices=YearTextChoice.choices,
        default=YearTextChoice.MP2I
    )

    def __str__(self):
        return self.subject.name.upper() + " " + self.name + " (" + self.get_year_display() + ")"

class Question(models.Model):

    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)

    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return self.question

cards/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Subject


# Create your views here.
class StartQuizView(TemplateView):
    template_name = "cards/start_quiz.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subjects"] = Subject.objects.order_by("name")
        return context

    def post(self, request):
        years = request.POST.getlist("year")
        if years == []:
            messages.add_message(request, messages.ERROR, "year_empty")
            return self.get(request)

        years = list(map(lambda y: "1" if y == "mp2i" else "2", years))

        subject_ids = request.POST.getlist("subjects")
        if subject_ids == []:
            messages.add_message(request, messages.ERROR, "subject_empty")
            return self.get(request)

        chapters_ids = []
        for subject_id in subject_ids:
            subject_chapters_ids = request.POST.getlist(f"chapters-{subject_id}")
            if subject_chapters_ids == []:
                messages.add_message(request, messages.ERROR, f"chapters_{subject_id}_empty")
                return self.get(request)

            chapters_ids += [
                int(subject_chapters_id)
                for subject_chapters_id in subject_chapters_ids
            ]

        number_of_questions = int(request.POST.get("nb-questions"))
        if number_of_questions < 1:
            messages.add_message(request, messages.ERROR, "nb_too_shorts")
            return self.get(request)

        # Get question ids
        questions = Question.objects.filter(chapter__pk__in=chapters_ids)

        if len(years) == 1:
            questions = questions.filter(chapter__year=years[0])

        questions = questions.order_by("?")[:number_of_questions]

        request.session["question_ids"] = [
            q.id for q in questions
        ]

        return redirect("cards:card")

class CardView(TemplateView):
    template_name = "cards/card.html"

    def get(self, request):
        question_ids = self.request.session.get("question_ids")
        if question_ids is None:
            messages.add_message(self.request, messages.ERROR, "invalid_session")
            return redirect("cards:start_quiz")

        if question_ids == []:
            messages.add_message(self.request, messages.INFO, "quiz_done")
            return redirect("cards:start_quiz")

        question_id = question_ids.pop(0)
        self.request.session["question_ids"] = question_ids
        context = {
            "question": Question.objects.get(pk=question_id)
        }

        return render(request, self.template_name, context)

class AddQuestion(LoginRequiredMixin, CreateView):
    model = Question
    template_name_suffix = "_add"
    fields = [
        "chapter",
        "question",
        "answer",
    ]
    success_url = reverse_lazy("cards:add")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subjects"] = Subject.objects.order_by("name")
        return context

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO, "success")
        return super().form_valid(form)

cards/templates/cards/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>Prépa Quiz</title>

        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdn.jsdelivr.net/npm/latex.js/dist/latex.js"></script>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
        {% block head %}
        {% endblock head %}
    </head>
    <body>
        <main class="flex items-center flex-col p-6">
            {% block main %}
            {% endblock main %}
        </main>
    </body>
</html>

cards/templates/cards/card.html
{% extends "cards/base.html" %}

{% load static %}

{% block head %}
<script type="text/javascript" src="{% static "js/card.js" %}"></script>
{% endblock head %}

{% block main %}
<div id="question" class="lg:w-3/4 sm:w-full flex flex-col items-center p-4 border rounded bg-slate-50 mt-6">
    <p class="latex-compile">{{ question.question }}</p>
    <a class="mt-4 py-1 bg-purple-600 rounded-full px-4 py-1 text-white hover:bg-purple-500">Voir la réponse</a>
</div>

<div id="answer" class="lg:w-3/4 sm:w-full flex flex-col items-center p-4 border rounded bg-slate-50 mt-6">
    <h1 class="text-xl">{{ question.chapter.subject.name }} : {{ question.chapter.name }} <span class="italic">{{ question.chapter.get_year_display }}</span></h1>
    <p class="italic latex-compile">{{ question.question }}</p>
    <p class="latex-compile">{{ question.answer }}</p>
    <a href="{% url "cards:card" %}" class="mt-4 py-1 bg-purple-600 rounded-full px-4 py-1 text-white hover:bg-purple-500">Question Suivante</a>
</div>
{% endblock main %}

cards/templates/cards/question_add.html
{% extends "cards/base.html" %}

{% load static %}

{% block head %}
<script type="text/javascript" src="{% static "js/add_question.js" %}"></script>
{% endblock head %}

{% block main %}
<form method="post" class="w-3/4 flex flex-col items-center p-4 border rounded bg-slate-50 mt-6">
    {% csrf_token %}
    
    <h1 class="text-xl mb-4">Ajouter une question</h1>

    {% for message in messages %}
        {% if message|stringformat:"s" == "success" %}
        <p class="text-sm text-green-400">Question ajoutée !</p>
        {% endif %}
    {% endfor %}

    <div class="mt-2">
        <label for="year">Année :</label>
        <select id="year" class="rounded-full bg-white border px-4 py-1">
            <option value="2">MPI</option>
            <option value="1">MP2I</option>
        </select>
    </div>

    <div class="mt-2">
        <label for="subject">Matière :</label>
        <select id="subject" class="rounded-full bg-white border px-4 py-1">
            {% for subject in subjects %}
            <option value="{{ subject.id }}">{{ subject.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="mt-2">
        <label for="chapter">Chapitre :</label>
        <select name="chapter" id="chapter" class="rounded-full bg-white border px-4 py-1" required>
            {% for subject in subjects %}
            {% for chapter in subject.chapter_set.all|dictsort:"name" %}
            <option value="{{ chapter.id }}" subject-id="{{ subject.id }}" year="{{ chapter.year }}">{{ chapter.name }}</option>
            {% endfor %}
            {% endfor %}
        </select>
    </div>

    <div class="mt-2 w-full flex flex-col items-center">
        <div class="flex w-4/5 justify-center">
            <label for="question" class="w-1/2 mr-2" required>Question :</label>
            <label for="question">Prévisualisation :</label>
        </div>
        <div class="flex w-4/5 justify-center">
            <textarea class="w-1/2 mr-2" name="question" id="question" cols="30" rows="10" latex-parent="question-preview"></textarea>
            <div class="bg-white w-1/2" id="question-preview"></div>
        </div>
    </div>

    <div class="mt-2 w-full flex flex-col items-center">
        <div class="flex w-4/5 justify-center">
            <label for="answer" class="w-1/2 mr-2" required>Réponse :</label>
            <label for="answer">Prévisualisation :</label>
        </div>
        <div class="flex w-4/5 justify-center">
            <textarea class="w-1/2 mr-2" name="answer" id="answer" cols="30" rows="10" latex-parent="answer-preview"></textarea>
            <div class="bg-white w-1/2" id="answer-preview"></div>
        </div>
    </div>

    <input type="submit" value="Ajouter" class="mt-4 py-1 bg-purple-600 rounded-full px-4 py-1 text-white hover:bg-purple-500" />
</form>
{% endblock main %}

cards/templates/cards/start_quiz.html
{% extends "cards/base.html" %}

{% load static %}

{% block head %}
<script type="text/javascript" src="{% static "js/start_quiz.js" %}"></script>
{% endblock head %}

{% block main %}
<h1 class="text-4xl">Prépa Quiz</h1>

<form method="post" class="lg:w-3/4 sm:w-full flex flex-col items-center p-4 border rounded bg-slate-50 mt-6">
    {% csrf_token %}

    <h2 class="text-2xl">Choisissez les paramètre du quiz</h2>

    {% for message in messages %}
        {% if message|stringformat:"s" == "invalid_session" %}
        <p class="text-sm text-red-400">Session invalide !</p>
        {% elif message|stringformat:"s" == "quiz_done" %}
        <p class="text-sm text-green-400">Quiz terminé !</p>
        {% endif %}
    {% endfor %}

    <div class="lg:w-1/2 sm:w-full mt-4">
        <div>
            <h3 class="text-xl">Années :</h3>

            {% for message in messages %}
                {% if message|stringformat:"s" == "year_empty" %}
                <p class="text-sm text-red-400">Au moins une année doit être cochée !</p>
                {% endif %}
            {% endfor %}
    
            <div class="pl-3">
                <input type="checkbox" name="year" value="mp2i" id="year-mp2i" checked show-attr="mp2i" />
                <label for="year-mp2i">MP2I</label>
            </div>
    
            <div class="pl-3">
                <input type="checkbox" name="year" value="mpi" id="year-mpi" checked show-attr="mpi" />
                <label for="year-mpi">MPI</label>
            </div>
        </div>

        <div class="mt-4">
            <h3 class="text-xl">Matières :</h3>

            {% for message in messages %}
                {% if message|stringformat:"s" == "subject_empty" %}
                <p class="text-sm text-red-400">Au moins une matières doit être cochée !</p>
                {% endif %}
            {% endfor %}

            {% for subject in subjects %}
            {% with subject.id|stringformat:"s" as subject_id %}
            <div class="border-t pl-3 py-1">
                <div class="flex justify-between items-center">
                    <div>
                        <input type="checkbox" name="subjects" value="{{ subject.id }}" id="subject-{{ subject.id }}" show-div="chapters-{{ subject.id }}" />
                        <label for="subject-{{ subject.id }}">{{ subject.name }}</label>
                    </div>
                    <a class="text-xs text-blue-600 hover:text-blue-400 cursor-pointer" unselect-all="chapters-{{ subject.id }}">Tous déséléctionner</a>
                </div>

                {% for message in messages %}       
                    {% if message|stringformat:"s" == "chapters_"|add:subject_id|add:"_empty" %}
                    <p class="text-sm text-red-400">Au moins un chapitre doit être coché !</p>
                    {% endif %}
                {% endfor %}

                <div id="chapters-{{ subject.id }}" class="pl-3">
                    {% for chapter in subject.chapter_set.all|dictsort:"name" %}
                    <div {{ chapter.get_year_display }}>
                        <input type="checkbox" name="chapters-{{ subject.id }}" value="{{ chapter.id }}" id="chapter-{{ chapter.id }}" checked />
                        <label for="chapter-{{ chapter.id }}"  class="text-xs">{{ chapter.name }} <span class="italic">{{ chapter.get_year_display }}</span></label>
                    </div>
                    {% empty %}
                    <p class="text-sm text-red-400">Aucun chapitre n'est disponible pour le moment</p>
                    {% endfor %}
                </div>
            </div>
            {% endwith %}
            {% endfor %}
        </div>

        <div class="mt-4">
            <div>
                <h3 class="text-xl">Nombre de question :</h3>

                {% for message in messages %}
                    {% if message|stringformat:"s" == "nb_too_shorts" %}
                    <p class="text-sm text-red-400">Le nombre de questions doit être supérieur à 1 !</p>
                    {% endif %}
                {% endfor %}
        
                <div class="pl-3">
                    <label for="nb-questions">Nombre de questions :</label>
                    <input type="number" name="nb-questions" value="25" id="nb-questions" min="1" class="border rounded-full px-2 remove-arrow w-12" />
                </div>
            </div>
        </div>
    </div>

    <input type="submit" value="Commencer" class="mt-4 py-1 bg-purple-600 rounded-full px-4 py-1 text-white hover:bg-purple-500">
</form>
{% endblock main %}